Repository Ayushpanditmoto/Trading-Bot, pull requests merged in 2024-05, with the labels that each got.

#3 Create Code_Of_Conduct.md
  Code_Of_Conduct.md
Labels: gssoc, level1

#32 Create contrinuting.md
  contrinuting.md
Labels: gssoc, level1

#37 Created a Login.py with functionality for login, logout and to show the demo balance
  frontend/image.png
  frontend/login.py
Labels: gssoc, level3

#39 Performed eda and visualizations
  tradingbot.ipynb
Labels: gssoc, level2

#42 requirements.txt
  requirements.txt
Labels: gssoc, level1

#50 GSSoC24: Bug fixes and Sign-Up feature for GUI
  frontend/login.py
  frontend/users.csv
Labels: gssoc, level3

#52 GSSoC24: rewritten GUI, added more feat
  .gitignore
  frontend/login.py
  requirements.txt
Labels: gssoc, level3

#54 Implementing Machine Learning for Trading Pattern Recognition using Technical Analysis #26
  data/sample.csv
  prediction/test2.py
  requirements.txt
Labels: gssoc, level3

#56 GSSoC'24: Added functions for Compounding & martingale
  frontend/login.py
Labels: gssoc, level3

#57 Typo Corrected
  contributing.md
Labels: gssoc, level1

#59 Implementing machine learning algorithm for Trading pattern recognition using LGBM
  prediction/crypto-forecasting-using-lgbm.ipynb
Labels: gssoc, level2

#61 feat: predicting IndusInd bank stocks
  .ipynb_checkpoints/TradingBotModelAccuracy-checkpoint.ipynb
  TradingBotModelAccuracy.ipynb
Labels: gssoc, level2

#72 Update README.md
  README.md
Labels: gssoc, level2
